# Generated by Django 3.2 on 2021-04-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
